# backtesting/engine/event_driven.py
"""
Event-driven backtesting engine.

Why event-driven instead of vectorized?
  Vectorized backtests process the entire time series at once. This makes
  lookahead bias easy to introduce accidentally (e.g., using tomorrow's
  open to fill today's signal). They also can't model partial fills,
  position limits, or intraday risk limits correctly.

  Event-driven processes one bar at a time, in chronological order.
  Every decision uses only data visible at that point in time.

Architecture:
  Each day produces two events:
    1. SIGNAL_EVENT  — generated by signal.compute() using data up to T-1
    2. FILL_EVENT    — executed at bar T open (arrival price)

  This enforces a one-bar execution delay: signal at close T-1, fill at open T.
  That's the realistic latency for an end-of-day strategy.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional

import pandas as pd

from backtesting.engine.fill_model import FillModel, FillResult
from backtesting.engine.cost_model import TransactionCostModel

logger = logging.getLogger(__name__)


@dataclass
class Position:
    symbol      : str
    qty         : float          # positive = long, negative = short
    avg_cost    : float          # average fill price
    entry_date  : pd.Timestamp

    @property
    def market_value(self) -> float:
        return self.qty * self.avg_cost   # updated externally via mark-to-market

    def is_long(self)  -> bool: return self.qty > 0
    def is_short(self) -> bool: return self.qty < 0
    def is_flat(self)  -> bool: return abs(self.qty) < 1e-6


@dataclass
class Trade:
    symbol      : str
    date        : pd.Timestamp
    side        : str          # 'buy' or 'sell'
    qty         : float
    fill        : FillResult
    pnl         : float = 0.0  # realised PnL when position closed


@dataclass
class PortfolioState:
    cash        : float
    positions   : Dict[str, Position]  = field(default_factory=dict)
    trades      : List[Trade]          = field(default_factory=list)
    equity_curve: List[dict]           = field(default_factory=list)

    def market_value(self, prices: Dict[str, float]) -> float:
        pos_value = sum(
            p.qty * prices.get(sym, p.avg_cost)
            for sym, p in self.positions.items()
        )
        return self.cash + pos_value

    def record_equity(self, date: pd.Timestamp, prices: Dict[str, float]) -> None:
        self.equity_curve.append({
            'date'  : date,
            'equity': self.market_value(prices),
            'cash'  : self.cash,
            'n_pos' : len(self.positions),
        })


class EventDrivenBacktester:
    """
    Event-driven backtesting engine.

    Usage:
        engine = EventDrivenBacktester(initial_capital=100_000)
        results = engine.run(
            price_data   = {symbol: ohlcv_df},   # index = date
            signal_fn    = my_signal.generate,   # (date, data_up_to_date) → {sym: weight}
            max_positions= 10,
        )
    """

    def __init__(
        self,
        initial_capital : float = 100_000,
        max_position_pct: float = 0.05,     # 5% max per position
        fill_model      : Optional[FillModel]           = None,
        cost_model      : Optional[TransactionCostModel] = None,
    ):
        self.initial_capital  = initial_capital
        self.max_position_pct = max_position_pct
        self.fill_model       = fill_model  or FillModel()
        self.cost_model       = cost_model  or TransactionCostModel()

    def run(
        self,
        price_data   : Dict[str, pd.DataFrame],
        signal_fn    : Callable[[pd.Timestamp, Dict[str, pd.DataFrame]], Dict[str, float]],
        start_date   : Optional[str] = None,
        end_date     : Optional[str] = None,
        max_positions: int = 10,
        rebalance_freq: str = 'W',   # 'D', 'W', 'M'
    ) -> 'BacktestResult':
        """
        Run the backtest.

        Parameters
        ----------
        price_data    : {symbol: DataFrame with columns [open,high,low,close,volume]}
                        All DataFrames must have DatetimeIndex.
        signal_fn     : Function(date, data_up_to_date) → {symbol: target_weight}
                        Weights sum to 1.0 for long-only; can be negative for short.
                        Called with data strictly BEFORE current date (no lookahead).
        start_date    : ISO date string or None (use earliest available)
        end_date      : ISO date string or None (use latest available)
        max_positions : maximum simultaneous positions
        rebalance_freq: how often to call signal_fn and rebalance ('D', 'W', 'M')

        Returns
        -------
        BacktestResult with equity curve, trades, and performance metrics
        """
        # Build unified date index (trading days only)
        all_dates = sorted(set.union(*[
            set(df.index) for df in price_data.values()
        ]))
        all_dates = pd.DatetimeIndex(all_dates).sort_values()

        if start_date:
            all_dates = all_dates[all_dates >= pd.Timestamp(start_date)]
        if end_date:
            all_dates = all_dates[all_dates <= pd.Timestamp(end_date)]

        if len(all_dates) < 20:
            raise ValueError(f'Too few trading days: {len(all_dates)}')

        portfolio = PortfolioState(cash=self.initial_capital)
        rebal_dates = self._get_rebalance_dates(all_dates, rebalance_freq)

        for i, date in enumerate(all_dates):
            # Current bar prices for mark-to-market
            current_prices = {}
            current_bars   = {}
            for sym, df in price_data.items():
                if date in df.index:
                    row = df.loc[date]
                    current_prices[sym] = float(row['close'])
                    current_bars[sym]   = row.to_dict()

            # On rebalance days: compute new target weights and trade
            if date in rebal_dates and i > 0:
                # Pass only data UP TO previous day — no lookahead
                data_up_to_prev = {
                    sym: df[df.index < date]
                    for sym, df in price_data.items()
                }
                try:
                    target_weights = signal_fn(date, data_up_to_prev)
                except Exception as e:
                    logger.warning(f'{date}: signal_fn failed ({e}) — holding current positions')
                    target_weights = {}

                if target_weights:
                    self._rebalance(
                        portfolio      = portfolio,
                        date           = date,
                        target_weights = target_weights,
                        current_bars   = current_bars,
                        current_prices = current_prices,
                        portfolio_value= portfolio.market_value(current_prices),
                        max_positions  = max_positions,
                    )

            # Mark to market at end of day
            portfolio.record_equity(date, current_prices)

        return BacktestResult(
            portfolio      = portfolio,
            initial_capital= self.initial_capital,
            price_data     = price_data,
        )

    def _get_rebalance_dates(
        self,
        dates          : pd.DatetimeIndex,
        freq           : str,
    ) -> set:
        """Generate rebalance dates at given frequency."""
        if freq == 'D':
            return set(dates)
        series = pd.Series(dates, index=dates)
        if freq == 'W':
            # First trading day of each week
            grouped = series.groupby(pd.Grouper(freq='W'))
            return set(g.min() for _, g in grouped if len(g) > 0)
        if freq == 'M':
            grouped = series.groupby(pd.Grouper(freq='MS'))
            return set(g.min() for _, g in grouped if len(g) > 0)
        raise ValueError(f'Unknown rebalance_freq: {freq}')

    def _rebalance(
        self,
        portfolio      : PortfolioState,
        date           : pd.Timestamp,
        target_weights : Dict[str, float],
        current_bars   : Dict[str, dict],
        current_prices : Dict[str, float],
        portfolio_value: float,
        max_positions  : int,
    ) -> None:
        """Execute trades to move toward target weights."""
        # Cap to max_positions by taking top abs(weight) symbols
        if len(target_weights) > max_positions:
            target_weights = dict(
                sorted(target_weights.items(), key=lambda x: abs(x[1]), reverse=True)
                [:max_positions]
            )

        # Sell positions not in target (exit first to free cash)
        for sym in list(portfolio.positions.keys()):
            if sym not in target_weights and sym in current_bars:
                self._close_position(portfolio, sym, date, current_bars[sym])

        # Buy/resize positions in target
        for sym, weight in target_weights.items():
            if sym not in current_bars:
                continue
            weight = max(min(weight, self.max_position_pct * 20), -self.max_position_pct * 20)
            target_value  = portfolio_value * weight
            target_qty    = target_value / current_prices.get(sym, 1.0)
            current_qty   = portfolio.positions.get(sym, Position(sym, 0, 0, date)).qty
            delta_qty     = target_qty - current_qty

            if abs(delta_qty) < 1:
                continue   # don't trade tiny adjustments

            side = 'buy' if delta_qty > 0 else 'sell'
            self._execute_order(portfolio, sym, side, abs(delta_qty), date, current_bars[sym])

    def _execute_order(
        self,
        portfolio: PortfolioState,
        symbol   : str,
        side     : str,
        qty      : float,
        date     : pd.Timestamp,
        bar      : dict,
    ) -> None:
        """Fill an order and update portfolio state."""
        fill = self.fill_model.simulate_fill(symbol, side, qty, bar)

        cost = fill.fill_price * fill.qty
        if side == 'buy':
            if cost > portfolio.cash:
                # Partial fill if insufficient cash
                affordable_qty = portfolio.cash / fill.fill_price
                if affordable_qty < 1:
                    return
                fill.qty = int(affordable_qty)
                cost = fill.fill_price * fill.qty

            portfolio.cash -= cost
            if symbol in portfolio.positions:
                pos = portfolio.positions[symbol]
                total_qty  = pos.qty + fill.qty
                pos.avg_cost = (
                    (pos.qty * pos.avg_cost + fill.qty * fill.fill_price) / total_qty
                    if total_qty != 0 else fill.fill_price
                )
                pos.qty = total_qty
            else:
                portfolio.positions[symbol] = Position(
                    symbol    = symbol,
                    qty       = fill.qty,
                    avg_cost  = fill.fill_price,
                    entry_date= date,
                )
        else:  # sell
            portfolio.cash += fill.fill_price * fill.qty
            if symbol in portfolio.positions:
                pos = portfolio.positions[symbol]
                realized_pnl = (fill.fill_price - pos.avg_cost) * fill.qty
                pos.qty -= fill.qty
                if abs(pos.qty) < 1e-6:
                    del portfolio.positions[symbol]
            else:
                realized_pnl = 0.0

            portfolio.trades.append(Trade(
                symbol = symbol,
                date   = date,
                side   = side,
                qty    = fill.qty,
                fill   = fill,
                pnl    = realized_pnl if side == 'sell' else 0.0,
            ))
            return

        portfolio.trades.append(Trade(
            symbol = symbol,
            date   = date,
            side   = side,
            qty    = fill.qty,
            fill   = fill,
        ))

    def _close_position(
        self,
        portfolio: PortfolioState,
        symbol   : str,
        date     : pd.Timestamp,
        bar      : dict,
    ) -> None:
        if symbol not in portfolio.positions:
            return
        pos = portfolio.positions[symbol]
        if pos.qty > 0:
            self._execute_order(portfolio, symbol, 'sell', pos.qty, date, bar)
        elif pos.qty < 0:
            self._execute_order(portfolio, symbol, 'buy', abs(pos.qty), date, bar)


@dataclass
class BacktestResult:
    portfolio      : PortfolioState
    initial_capital: float
    price_data     : Dict[str, pd.DataFrame]

    @property
    def equity_curve(self) -> pd.DataFrame:
        return pd.DataFrame(self.portfolio.equity_curve).set_index('date')

    @property
    def trades(self) -> pd.DataFrame:
        if not self.portfolio.trades:
            return pd.DataFrame()
        rows = []
        for t in self.portfolio.trades:
            rows.append({
                'date'        : t.date,
                'symbol'      : t.symbol,
                'side'        : t.side,
                'qty'         : t.qty,
                'fill_price'  : t.fill.fill_price,
                'arrival_price': t.fill.arrival_price,
                'is_bps'      : t.fill.is_bps,
                'pnl'         : t.pnl,
            })
        return pd.DataFrame(rows)

    @property
    def final_equity(self) -> float:
        eq = self.equity_curve
        return float(eq['equity'].iloc[-1]) if len(eq) else self.initial_capital
