#!/bin/bash
# scripts/setup_nginx_tls.sh
# Phase 2C: Install nginx + Let's Encrypt TLS in front of the dashboard
#
# Prerequisites:
#   1. You have a domain name pointing to 67.205.185.84 (e.g. dashboard.yourdomain.com)
#   2. Port 80 and 443 are open in the firewall
#
# Run as root:
#   DOMAIN=dashboard.yourdomain.com EMAIL=you@email.com bash scripts/setup_nginx_tls.sh

set -euo pipefail

DOMAIN="${DOMAIN:-}"
EMAIL="${EMAIL:-}"
DASHBOARD_PORT=8050

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
    echo "❌ Usage: DOMAIN=dashboard.example.com EMAIL=admin@example.com bash $0"
    exit 1
fi

echo "=============================================="
echo " AlphaEdge — nginx + TLS Setup"
echo " Domain: $DOMAIN"
echo " Email:  $EMAIL"
echo "=============================================="

# ── Install nginx and certbot ──────────────────────────────────────────────────
apt-get update -qq
apt-get install -y nginx certbot python3-certbot-nginx --quiet
echo "✅ nginx + certbot installed"

# ── Block direct port 8050 access ─────────────────────────────────────────────
ufw deny 8050 2>/dev/null || true
echo "✅ ufw: port 8050 blocked (dashboard only accessible via nginx)"

# ── Write nginx config ─────────────────────────────────────────────────────────
cat > "/etc/nginx/sites-available/alphaedge" <<NGINX
# AlphaEdge Dashboard — nginx reverse proxy with TLS
# Generated by scripts/setup_nginx_tls.sh

# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# HTTPS with TLS
server {
    listen 443 ssl;
    server_name ${DOMAIN};

    # TLS — managed by certbot
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer-when-downgrade always;

    # Basic auth to protect dashboard (change password in next step)
    auth_basic "AlphaEdge Dashboard";
    auth_basic_user_file /etc/nginx/.alphaedge_htpasswd;

    # Proxy to dashboard
    location / {
        proxy_pass         http://127.0.0.1:${DASHBOARD_PORT};
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    # Webhook endpoint — no auth (has its own secret)
    location /webhook {
        auth_basic off;
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/alphaedge /etc/nginx/sites-enabled/alphaedge
rm -f /etc/nginx/sites-enabled/default
echo "✅ nginx config written"

# ── Set up HTTP basic auth ─────────────────────────────────────────────────────
# Generate a random password
DASH_PASS=$(openssl rand -base64 18)
echo "alphaedge:$(openssl passwd -apr1 "$DASH_PASS")" > /etc/nginx/.alphaedge_htpasswd
chmod 640 /etc/nginx/.alphaedge_htpasswd
echo "✅ Dashboard basic auth configured"
echo "   Username: alphaedge"
echo "   Password: ${DASH_PASS}"
echo "   ⚠️  Save this password — it will not be shown again"

# ── Obtain TLS certificate ─────────────────────────────────────────────────────
# Test nginx config first
nginx -t
systemctl reload nginx

certbot --nginx \
    --non-interactive \
    --agree-tos \
    --email "$EMAIL" \
    --domains "$DOMAIN" \
    --redirect
echo "✅ Let's Encrypt TLS certificate obtained for $DOMAIN"

# ── Set up auto-renewal ────────────────────────────────────────────────────────
systemctl enable certbot.timer 2>/dev/null || \
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet") | crontab -
echo "✅ Auto-renewal configured"

echo ""
echo "=============================================="
echo " TLS Setup Complete!"
echo " Dashboard: https://${DOMAIN}"
echo " Username:  alphaedge"
echo " Password:  ${DASH_PASS}"
echo " Direct port 8050 is BLOCKED"
echo "=============================================="
